### ISSUE TITLE
Fortschritte oder aufgegeben?

### ISSUE THREAD

**Issue by jvoigtlaender** [Dinendal92/Abschlussprojekt-DP2016#3]

**Comment by moosmannp** [comment]
Ich habe mal meine Html datei hochgeladen. Leider hab ich nicht wirklich viel geschafft bisher, da ich meine Priorität eher auf die Pflichtmodule dieses Semesters gelegt habe. Ich werden versuchen in den nächsten Tagen weiterzukommen, um eventuell doch noch die Klausurzulassung zu erhalten.
