### ISSUE TITLE
elm-package.json und Organisation des Quellcodes

### ISSUE THREAD

**Issue by jvoigtlaender** [Dinendal92/Abschlussprojekt-DP2016#4]
Bitte fügen Sie die `elm-package.json` Datei dem Repository hinzu, damit alle Abhängigkeiten klar sind, auch für lokales Kompilieren des Projekts.

Zur Organisation des Quellcodes: Üblich wäre, `.elm` Dateien in ein Unterverzeichnis `src` zu verschieben, und in `elm-package.json` das `"."` in `"source-directories"` durch `"src"` zu ersetzen.

**Comment by moosmannp** [comment]
elm-package.json hinzugefügt
