### ISSUE TITLE
Umgang mit Subscriptions

### ISSUE THREAD

**Issue by jvoigtlaender** [Dinendal92/Abschlussprojekt-DP2016#5]
... scheint mir sehr dubios. Schon allein, dass Sie soviel "Logik" in der `subscriptions`-Funktion haben, ist sehr ungewöhnlich. Üblicherweise würde dort aufgezählt, von welchen externen Quellen das Verhalten in welchem Zustand abhängt, aber jede Logik etwa zu Zustandsübergängen gehört in die `update`-Funktion.

Und dass da die ganzen `Time.every`-Aufrufe mit `millisecond` oder `1.1 * millisecond` stehen, ist auch ein deutliches Zeichen für einen falschen Ansatz.  Lesen Sie nochmal die Dokumentation http://package.elm-lang.org/packages/elm-lang/core/4.0.3/Time#every, die Funktion ist nicht für sowas gemacht wofür Sie es zu benutzen versuchen.

Ohne genauere Erklärung, was Sie dort eigentlich zu erreichen versuchen, kann ich erstmal nur vorschlagen, sich folgende beide Funktionen anzuschauen. Gut möglich, dass Sie eigentlich `Time.now` (zusammen mit `Task.Extra.performFailproof` aus http://package.elm-lang.org/packages/NoRedInk/elm-task-extra) oder `Cmd.Extra.message` möchten. Beide würden aus der `update`-Funktion heraus getriggert und dann eine Message erzeugen, die neu in die `update`-Funktion hineinfließt .
- http://package.elm-lang.org/packages/elm-lang/core/4.0.3/Time#now (und http://package.elm-lang.org/packages/NoRedInk/elm-task-extra/2.0.0/Task-Extra#performFailproof)
- http://package.elm-lang.org/packages/shmookey/cmd-extra/1.0.0/Cmd-Extra#message

Zu letzterem sei auch auf http://faq.elm-community.org/17.html#how-do-i-generate-a-new-message-as-a-command hingewiesen.

**Comment by moosmannp** [comment]
"Logik" aus Subscriptions entfernt.
Die Time.every Aufrufe muss ich mir nochmal anschauen, bisher hab ich es leider nicht anders hinbekommen, als jede Millisekunde zu überprüfen, ob ein Ereignis eingetroffen ist oder nicht.
